# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: demo.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'demo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndemo.proto\x12\x08oteldemo\"0\n\x08\x43\x61rtItem\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"a\n\x07\x41\x64\x64ress\x12\x16\n\x0estreet_address\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x04 \x01(\t\x12\x10\n\x08zip_code\x18\x05 \x01(\t\"<\n\x05Money\x12\x15\n\rcurrency_code\x18\x01 \x01(\t\x12\r\n\x05units\x18\x02 \x01(\x03\x12\r\n\x05nanos\x18\x03 \x01(\x05\"\x90\x01\n\x0e\x43reditCardInfo\x12\x1a\n\x12\x63redit_card_number\x18\x01 \x01(\t\x12\x17\n\x0f\x63redit_card_cvv\x18\x02 \x01(\x05\x12#\n\x1b\x63redit_card_expiration_year\x18\x03 \x01(\x05\x12$\n\x1c\x63redit_card_expiration_month\x18\x04 \x01(\x05\"L\n\tOrderItem\x12 \n\x04item\x18\x01 \x01(\x0b\x32\x12.oteldemo.CartItem\x12\x1d\n\x04\x63ost\x18\x02 \x01(\x0b\x32\x0f.oteldemo.Money\"\xb6\x01\n\x0bOrderResult\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x1c\n\x14shipping_tracking_id\x18\x02 \x01(\t\x12&\n\rshipping_cost\x18\x03 \x01(\x0b\x32\x0f.oteldemo.Money\x12+\n\x10shipping_address\x18\x04 \x01(\x0b\x32\x11.oteldemo.Address\x12\"\n\x05items\x18\x05 \x03(\x0b\x32\x13.oteldemo.OrderItem\"\x9d\x01\n\x11PlaceOrderRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x15\n\ruser_currency\x18\x02 \x01(\t\x12\"\n\x07\x61\x64\x64ress\x18\x03 \x01(\x0b\x32\x11.oteldemo.Address\x12\r\n\x05\x65mail\x18\x05 \x01(\t\x12-\n\x0b\x63redit_card\x18\x06 \x01(\x0b\x32\x18.oteldemo.CreditCardInfo\":\n\x12PlaceOrderResponse\x12$\n\x05order\x18\x01 \x01(\x0b\x32\x15.oteldemo.OrderResult2\\\n\x0f\x43heckoutService\x12I\n\nPlaceOrder\x12\x1b.oteldemo.PlaceOrderRequest\x1a\x1c.oteldemo.PlaceOrderResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'demo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CARTITEM']._serialized_start=24
  _globals['_CARTITEM']._serialized_end=72
  _globals['_ADDRESS']._serialized_start=74
  _globals['_ADDRESS']._serialized_end=171
  _globals['_MONEY']._serialized_start=173
  _globals['_MONEY']._serialized_end=233
  _globals['_CREDITCARDINFO']._serialized_start=236
  _globals['_CREDITCARDINFO']._serialized_end=380
  _globals['_ORDERITEM']._serialized_start=382
  _globals['_ORDERITEM']._serialized_end=458
  _globals['_ORDERRESULT']._serialized_start=461
  _globals['_ORDERRESULT']._serialized_end=643
  _globals['_PLACEORDERREQUEST']._serialized_start=646
  _globals['_PLACEORDERREQUEST']._serialized_end=803
  _globals['_PLACEORDERRESPONSE']._serialized_start=805
  _globals['_PLACEORDERRESPONSE']._serialized_end=863
  _globals['_CHECKOUTSERVICE']._serialized_start=865
  _globals['_CHECKOUTSERVICE']._serialized_end=957
# @@protoc_insertion_point(module_scope)
